# Generated by Django 5.0.6 on 2024-07-10 18:50

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0002_alter_service_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='service_title', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.ImageField(upload_to='static/ServicesApp/uploads'),
        ),
    ]
