# Generated by Django 5.0.6 on 2024-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0003_service_service_slug_alter_service_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_file',
            field=models.FileField(default=None, null=True, upload_to='ServicesApp/uploads/files'),
        ),
    ]
