# Generated by Django 5.0.6 on 2024-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='reg_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
