TITLE Page_93: IBM Character Display
.MODEL SMALL
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS, AX

    MOV AH,2
    MOV CX,256
    MOV DL,14 ; PRINT THE ASCII CHARACTERS AFTER CARRIAGE RETURN WHICH HAS ACII VALUE OF 13D
Loop_Label:
    INT 21H
    INC DL
    DEC CX
    JNZ Loop_Label

    MOV AH,4CH
    INT 21H
MAIN ENDP
    END MAIN