TITLE Experiment_no 5: PROG_2
.MODEL SMALL
.STACK 100H
.DATA
MSG1 DB "ENTER A BINARY NUMBER: $"

.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    ;PROMPT
    LEA DX,MSG1
    MOV AH,9
    INT 21H

    ;INPUT
    MOV AH,1 
    INT 21H 
    ;AL NOW HAS INPUT
    XOR BL,BL ;CLEARS BL SO THAT IT CAN HOLD THE BINARY NUMBER (8 BITS MAX)
    XOR CL,CL ;CLEARS CX SO THAT IT CAN HOLD NO OF 1s in the BINARY NUMBER

    LABEL_WHILE:
    CMP AL,0DH ; IS CARRAIGE RETURN ?
    JE DONE
    ;INPUT CONTINUES
    ;AND AL,0FH ; or SUB AL,'0'  , AL NOW HAS CONVERTED ASCII VALUE OF INPUT WHICH IS 0 / 1 (NOT '0' / '1')
    SUB AL,'0' 
    SHL BL,1 ; MAKE ROOM AT LSB
    OR BL,AL ; ADD THE INPUT BIT TO LSB
    ADD CL,AL ; COUNT 1 
    INT 21H ; TAKE NEW INPUT
    JMP LABEL_WHILE
    DONE:
    ;HERE BL HOLDS THE BINARY INPUT and CL HOLS NUMBER OF 1 s in it
    ;NEW LINE
    MOV AH,2
    MOV DL,0AH
    INT 21H
    MOV DL,0DH
    INT 21H
    ;PRINT NUMBER OF 1 s
    MOV AH,2
    ADD CL,'0' ; NUMBER TO ASCII
    MOV DL,CL
    INT 21H


    MAIN ENDP
    END MAIN
